# Changes here will be overwritten by Copier
_commit: 2e4f7d0
_src_path: gh:34j/pypackage-template
add_me_as_contributor: false
cli_name: biem-helmholtz-2d
copyright_year: '2025'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: ultrasphere-dev
github_app_installation_ids: ''
github_username: ultrasphere-dev
has_cli: true
initial_commit: false
is_django_package: false
open_source_license: MIT
open_with_editor: true
package_name: biem_helmholtz_2d
project_name: biem-helmholtz-2d
project_short_description: Acoustic scattering from analytic 2D shapes in NumPy /
    PyTorch (Kress 1991)
project_slug: biem-helmholtz-2d
run_uv_sync: false
setup_github: false
setup_pre_commit: false

